// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRGpWjnWtk18_AzPBZ5i9gDUN9Ngq2Fc',
    appId: '1:240728397258:web:c7de119a00533d2d85ab33',
    messagingSenderId: '240728397258',
    projectId: 'convertor-app-a7d37',
    authDomain: 'convertor-app-a7d37.firebaseapp.com',
    storageBucket: 'convertor-app-a7d37.firebasestorage.app',
    measurementId: 'G-W6DPZMQ2XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TmlBl5Kbp0HgyoWUQ9rFMkEqluTuPdY',
    appId: '1:240728397258:android:66979f133b72397b85ab33',
    messagingSenderId: '240728397258',
    projectId: 'convertor-app-a7d37',
    storageBucket: 'convertor-app-a7d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjBguRfCA8VDJNHIWTgq02vz8QUb9skk',
    appId: '1:240728397258:ios:603abd389ccd5d7585ab33',
    messagingSenderId: '240728397258',
    projectId: 'convertor-app-a7d37',
    storageBucket: 'convertor-app-a7d37.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjBguRfCA8VDJNHIWTgq02vz8QUb9skk',
    appId: '1:240728397258:ios:603abd389ccd5d7585ab33',
    messagingSenderId: '240728397258',
    projectId: 'convertor-app-a7d37',
    storageBucket: 'convertor-app-a7d37.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcRGpWjnWtk18_AzPBZ5i9gDUN9Ngq2Fc',
    appId: '1:240728397258:web:b08a57625145ae0a85ab33',
    messagingSenderId: '240728397258',
    projectId: 'convertor-app-a7d37',
    authDomain: 'convertor-app-a7d37.firebaseapp.com',
    storageBucket: 'convertor-app-a7d37.firebasestorage.app',
    measurementId: 'G-CW775VNLXJ',
  );
}
